language: node_js

node_js:
  - '10'

env:
  global:
  - USER="jimzhan"
  - EMAIL="jim.zhan@me.com"
  - REPO="convict-register"
  - GH_REPO="github.com/${USER}/${REPO}.git"

deploy:
  provider: npm
  email: jim.zhan@me.com
  api_key: $NPM_TOKEN
  on:
    tags: true

before_script:
  - npm install --global makeshift && makeshift -s @bcoe -r registry.npmjs.org

install:
  - npm install

script:
  - npm run test

after_success:
  - npm publish --verbose
