language: node_js

node_js:
  - '10'

deploy:
  provider: npm
  email: jim.zhan@me.com
  api_key: $NPM_TOKEN
  on:
    tags: true

before_script:
  - npm install --global makeshift && makeshift -s @bcoe -r registry.npmjs.org

install:
  - npm install

script:
  - npm run test
  - npm run release
  - git push origin master
  - git push origin master --tags

after_success:
  - npm publish --verbose
